# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    packageType: "sdk"
    version: '2.1.300' # replace this value with the version that you need for your project
  displayName: 'Install DotNet'
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    .paket\paket.exe restore
    npm install
    npm run build
  displayName: 'Build'
